
disabled_rules:
    - trailing_whitespace
    - identifier_name
    - force_cast
    - line_length
    - closure_parameter_position
    - function_body_length
    - opening_brace
    - type_body_length
    
excluded:
    - Pods
